spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tp_spring_api
    username: Ton_User
    password: Ton_MDP
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
